name: BagOfGoldCore
main: one.lindegaard.BagOfGoldCore.BagOfGoldCore
version: ${version}
description: BagOfGoldCore is a shared Library for BagOfGold and MobHunting. 
dev-url: https://github.com/Rocologo/BagOfGoldCore
author: Rocologo
depend: []
loadbefore: [BagOfGold, MobHunting]
softdepend: []
api-version: 1.13

commands:
  bagcore:
    description: Allows you to configure BagOfGoldCore
    permission: bagofgoldcore.cmd
    aliases: [bagc]
    usage: /<command> command

permissions:
  bagcore.cmd:
    description: Allows a player to use the mobhunt command
    default: true
  bagcore.update:
    description: Allows a player to update the plugin
    default: op
    children:
      bagcore.cmd: true
  bagcore.reload:
    description: Allows you to reload the configuration
    default: op
    children:
      bagcore.cmd: true
  bagcore.version:
    description: Allows you to get plugin version.
    default: true
    children:
      bagcore.cmd: true
  bagcore.debug:
    description: Allows you to enable/disable debugmode and see debug information in the server console.
    default: op
    children:
      bagcore.cmd: true
  bagcore.mute:
    description: Allows you to mute/unmute BagOfGoldCore sending messages.
    default: true
    children:
      bagcore.cmd: true
  