name: BagOfGold
main: one.lindegaard.BagOfGold.BagOfGold
version: ${version}
description: BagOfGold is an Item based eConomy plugin, which replace Essentials Economy, craftConomy, Gringotts and similar plugins. Your money is in the Bag so be careful that you not loose the bag when you die. You can save some of your money the BagOfGold bank or in a protected chest. 
dev-url: http://dev.bukkit.org/server-mods/bagofgold/
author: Rocologo
depend: []
loadbefore: [PerWorldInventory, Citizens2, Essentials, MobHunting, ItemFrameShops]
softdepend: [ActionAnnouncer, ActionBarAPI, Actionbar, TitleAPI, TitleManager, PlaceholderAPI]
api-version: 1.13

commands:
  bagofgold:
    description: Allows you to configure mobhunt
    permission: bagofgold.cmd
    aliases: [bag,bog,bgold,money]
    usage: /<command> command

permissions:
  bagofgold.cmd:
    description: Allows a player to use the mobhunt command
    default: true
  bagofgold.update:
    description: Allows a player to update the plugin
    default: op
    children:
      bagofgold.cmd: true
  bagofgold.reload:
    description: Allows you to reload the configuration
    default: op
    children:
      bagofgold.cmd: true
  bagofgold.version:
    description: Allows you to get plugin version.
    default: true
    children:
      bagofgold.cmd: true
  bagofgold.debug:
    description: Allows you to enable/disable debugmode and see debug information in the server console.
    default: op
    children:
      bagofgold.cmd: true
  bagofgold.money:
    description: Allows you to drop money and give/take money to/from the players.
    default: op
    children:
      bagofgold.cmd: true
  bagofgold.convert:
    description: Allows you to convert some data.
    default: op
    children:
      bagofgold.cmd: true
      